### ISSUE TITLE
Value out of range for datatype  java.lang.Integer for column `cardinality`.

### ISSUE THREAD

**Issue by Skad00dle** [artur-tamazian/avro-schema-generator#25] opened 2021-04-22 04:54 UTC
While generating avro schemas for some tables it is failing with above error.

from initial debugging it looks like it is using integer datatype to store values fetched from `cardinality` column from information_schema.statistics table. i am guessing this is called when trying to fetch index metadata from db.
attaching more error logs for your reference.

Caused by: com.mysql.cj.exceptions.NumberOutOfRange: Value '2589011712' is outside of valid range for type java.lang.Integer

warn: Could not read integer value for column <cardinality> </cardinality>

java.sql.SQLDataException: Value '2589011712' is outside of valid range for type java.lang.Integer
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
App > at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
App > at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:92)
App > at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1411)
App > at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:816)
App > at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:837)
App > at schemacrawler.crawl.MetadataResultSet.getInt(MetadataResultSet.java:340)
App > at schemacrawler.crawl.IndexRetriever.createIndexForTable(IndexRetriever.java:182)
App > at schemacrawler.crawl.IndexRetriever.createIndexes(IndexRetriever.java:146)
App > at schemacrawler.crawl.IndexRetriever.retrieveIndexesFromMetadata(IndexRetriever.java:343)
App > at schemacrawler.crawl.IndexRetriever.retrieveIndexesFromMetadata(IndexRetriever.java:359)
App > at schemacrawler.crawl.IndexRetriever.retrieveIndexes(IndexRetriever.java:98)
App > at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$22(SchemaCrawler.java:615)
App > at sf.util.StopWatch.time(StopWatch.java:177)
App > at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:609)
App > at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:766)
App > at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:89)
App > at com.at.avro.DbSchemaExtractor.get(DbSchemaExtractor.java:71)
App > at com.at.avro.DbSchemaExtractor.getForTables(DbSchemaExtractor.java:49)

note: i am very new to github OSS. please ignore my mistakes and please let me know if you need any more info on this.
Thanks

**Comment by artur-tamazian** [comment] 2021-04-22 06:59
What's the version of MySQL that you're using?

**Comment by Skad00dle** [comment] 2021-04-22 07:06
we are running AWS RDS with mysql version 8.0.21.
and using avro schema generator version 1.0.6

**Comment by artur-tamazian** [comment] 2021-04-22 15:07
Can you please run `SHOW CREATE TABLE information_schema.STATISTICS;`? Just want to confirm the correct type of the column. 

I believe it's a bug in the SchemaCrawler library that is used. It expects Integer type [here](https://github.com/schemacrawler/SchemaCrawler/blob/d8e2a16b2ec748c879bdec636bd1d58f5a6bdb53/schemacrawler-api/src/main/java/schemacrawler/crawl/IndexRetriever.java#L121). Once we know what is the actual type we can file a bug for SchemaCrawler to fix.

**Comment by Skad00dle** [comment] 2021-04-23 03:53
`SHOW CREATE TABLE information_schema.STATISTICS;`

result: 

`CREATE ALGORITHM=UNDEFINED DEFINER=`mysql.infoschema`@`localhost` SQL SECURITY DEFINER VIEW `information_schema`.`STATISTICS` AS select `cat`.`name` AS `TABLE_CATALOG`,`sch`.`name` AS `TABLE_SCHEMA`,`tbl`.`name` AS `TABLE_NAME`,if(((`idx`.`type` = 'PRIMARY') or (`idx`.`type` = 'UNIQUE')),0,1) AS `NON_UNIQUE`,`sch`.`name` AS `INDEX_SCHEMA`,(`idx`.`name` collate utf8_tolower_ci) AS `INDEX_NAME`,`icu`.`ordinal_position` AS `SEQ_IN_INDEX`,if((`col`.`hidden` = 'SQL'),NULL,(`col`.`name` collate utf8_tolower_ci)) AS `COLUMN_NAME`,(case when (`icu`.`order` = 'DESC') then 'D' when (`icu`.`order` = 'ASC') then 'A' else NULL end) AS `COLLATION`,internal_index_column_cardinality(`sch`.`name`,`tbl`.`name`,`idx`.`name`,`col`.`name`,`idx`.`ordinal_position`,`icu`.`ordinal_position`,if((`tbl`.`partition_type` is null),`tbl`.`engine`,''),`tbl`.`se_private_id`,((`tbl`.`hidden` <> 'Visible') or (0 <> `idx`.`hidden`) or (0 <> `icu`.`hidden`)),coalesce(`stat`.`cardinality`,cast(-(1) as unsigned)),coalesce(cast(`stat`.`cached_time` as unsigned),0)) AS `CARDINALITY`,get_dd_index_sub_part_length(`icu`.`length`,`col`.`type`,`col`.`char_length`,`col`.`collation_id`,`idx`.`type`) AS `SUB_PART`,NULL AS `PACKED`,if((`col`.`is_nullable` = 1),'YES','') AS `NULLABLE`,(case when (`idx`.`type` = 'SPATIAL') then 'SPATIAL' when (`idx`.`algorithm` = 'SE_PRIVATE') then '' else `idx`.`algorithm` end) AS `INDEX_TYPE`,if(((`idx`.`type` = 'PRIMARY') or (`idx`.`type` = 'UNIQUE')),'',if(internal_keys_disabled(`tbl`.`options`),'disabled','')) AS `COMMENT`,`idx`.`comment` AS `INDEX_COMMENT`,if(`idx`.`is_visible`,'YES','NO') AS `IS_VISIBLE`,if((`col`.`hidden` = 'SQL'),`col`.`generation_expression_utf8`,NULL) AS `EXPRESSION` from (((((((`mysql`.`index_column_usage` `icu` join `mysql`.`indexes` `idx` on((`idx`.`id` = `icu`.`index_id`))) join `mysql`.`tables` `tbl` on((`idx`.`table_id` = `tbl`.`id`))) join `mysql`.`columns` `col` on((`icu`.`column_id` = `col`.`id`))) join `mysql`.`schemata` `sch` on((`tbl`.`schema_id` = `sch`.`id`))) join `mysql`.`catalogs` `cat` on((`cat`.`id` = `sch`.`catalog_id`))) join `mysql`.`collations` `coll` on((`tbl`.`collation_id` = `coll`.`id`))) left join `mysql`.`index_stats` `stat` on(((`tbl`.`name` = `stat`.`table_name`) and (`sch`.`name` = `stat`.`schema_name`) and (`idx`.`name` = `stat`.`index_name`) and (`col`.`name` = `stat`.`column_name`)))) where ((0 <> can_access_table(`sch`.`name`,`tbl`.`name`)) and (0 <> is_visible_dd_object(`tbl`.`hidden`,((0 <> `idx`.`hidden`) or (0 <> `icu`.`hidden`))))) |  
-- | --`

**Comment by artur-tamazian** [comment] 2021-04-24 21:43
Thanks for the info! 

`avro-schema-generator` is using `SchemaCrawler` library which seems to have a bug that you have found. I've filed a bug report  which you can follow [here](https://github.com/schemacrawler/SchemaCrawler/issues/461) (please provide any additional information they may need to fix). 

Once the issue is fixed in `SchemaCrawler` I'll update `avro-schema-generator` and release a new version.

**Comment by artur-tamazian** [comment] 2021-04-26 05:48
The issue in SchemaCrawler has been fixed. I've released a new version that contains a fix. Please use version [1.0.7](https://search.maven.org/artifact/com.github.artur-tamazian/avro-schema-generator).

**Closed by artur-tamazian** 2021-04-26 05:48 UTC

**Comment by Skad00dle** [comment] 2021-04-26 07:39
Thanks @artur-tamazian for fixing this on a short turn around time.
